User:
  Path: "import_jms_from_qz_excel/files/users.xlsx"
  # 从 1 开始数数，数据从 HeaderRowNum + 1 行读取
  HeaderRowNum: 1

UserGroup:
  Path: "import_jms_from_qz_excel/files/groups.xlsx"
  # 从 1 开始数数，数据从 HeaderRowNum + 1 行读取
  HeaderRowNum: 1

Asset:
  Path: "import_jms_from_qz_excel/files/assets.xlsx"
  # 从 1 开始数数，数据从 HeaderRowNum + 1 行读取
  HeaderRowNum: 1

Account:
  Path: "import_jms_from_qz_excel/files/accounts.xlsx"
  # 从 1 开始数数，数据从 HeaderRowNum + 1 行读取
  HeaderRowNum: 1

Node:
  Path: "import_jms_from_qz_excel/files/nodes.xlsx"
  # 从 1 开始数数，数据从 HeaderRowNum + 1 行读取
  HeaderRowNum: 1

Permission:
  Path: "import_jms_from_qz_excel/files/permissions.xlsx"
  # 从 1 开始数数，数据从 HeaderRowNum + 1 行读取
  HeaderRowNum: 1

JumpServer:
  Endpoint: "http://127.0.0.1"
  # Token 获取方式: https://docs.jumpserver.org/zh/v4/dev/rest_api/#2-api -> Private Token
  Token: "09c4264f8d9f58ff596b106fd0bec251ac0c5e49"
  # 不填默认为 Default 组织
  OrgId: "02d43e43-6851-4d01-90cf-589fb63d53e5"
  # 本地用户默认设置的密码
  DefaultPassword: "jumpserver123"
  # ACL 禁用是否包含 admin 用户
  ACLLoginDenyIncludeAdmin: true
